version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/config/
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true